name: Discord PR Notification

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  send_discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR to Discord
        uses: peter-evans/discord-webhook-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            New pull request created: ${{ github.event.pull_request.title }}
            PR URL: ${{ github.event.pull_request.html_url }}
            Created by: ${{ github.event.pull_request.user.login }}
